language: node_js
node_js:
  - "node"
dist: trusty
sudo: required
branches:
  only:
    - master
before_install:
  - chmod a+x ./scripts/install.sh
  - chmod a+x ./scripts/run-test.sh
  - chmod a+x ./scripts/after-build.sh
script:
  - ./scripts/install.sh
  - ./scripts/run-test.sh  
after_success:
  - ./scripts/after-build.sh
notifications:
  email:
    on_success: never
    on_failure: always