language: node_js
dist: trusty
sudo: required
branches:
  only:
    - master
before_install:
  - chmod a+x ./scripts/travis-build.sh
  - chmod a+x ./scripts/run-tests.sh
  - chmod a+x ./scripts/after-build.sh
script:
  - ./scripts/run-tests.sh
  - ./scripts/travis-build.sh
after_success:
  - ./scripts/after-build.sh
notifications:
  email:
    on_success: never
    on_failure: always